### ISSUE TITLE
tutorial dataset details need to be moved to datasets_index.rst

### ISSUE THREAD

**Issue by kalenkovich** [dominikwelke/mne-python#12]
See these comments by @larsoner:

- https://github.com/mne-tools/mne-python/pull/8867#discussion_r577008586
- https://github.com/mne-tools/mne-python/pull/8867#discussion_r577009818
- https://github.com/mne-tools/mne-python/pull/8867#discussion_r577010433

**Comment by dominikwelke** [comment]
closed by 68ba9109e42d573ef5736e414f809673de694d5f and 6b8ef202396ea2138fb29cdaf9172374c9e9ce49
