### ISSUE TITLE
better/nicer plots

### ISSUE THREAD

**Issue by dominikwelke** [dominikwelke/mne-python#2]
lets polish the plots to look nices/more informative and introduce stem plots for average snr

**Comment by dominikwelke** [comment]
fyi, i recently pushed some of my analysis code to another public repo. just the tools to do what we do here as well, but all in function / module format.

when i did this, i updated the snr spectrum plot a little. 
it plots average snr as stem plots now, and optionally underlays trial and/or channel averages in different colors.
not a lot prettier, but you might start from there if you want to modify thing.

its the `plot_snr_spectrum` function here: 
https://github.com/dominikwelke/mne-frequency-tagging/blob/4f08127b1d1bd766dbe5b89d214b2765e0a0d5a4/mne_frequency_tagging/frequency_tagging.py#L120-L179

**Comment by kalenkovich** [comment]
I'll definitely start from that code, thanks!

**Comment by kalenkovich** [comment]
I really hate plotting 😆

It just does not look well with the current number of frequencies on the plot. We might want to downsample the signal to lower the resolution.

With the current resolution, the stem plot for the "grand average" does not mix well with any background snrs. It does not look well by itself even. This is the best I was able to do for a standalone stem plot:

![image](https://user-images.githubusercontent.com/9257050/99580640-c0e42880-29f0-11eb-9625-89cfa38ed73a.png)

For a plot with background snrs, I went with the line plot for both:

![image](https://user-images.githubusercontent.com/9257050/99580771-e8d38c00-29f0-11eb-891f-48e5d9bcf0eb.png)

I tried using lighter colors and/or transparency for the background snrs but grey worked the best so far.

I also tried looking at plots in some papers but they all have much fewer frequencies.

**Comment by kalenkovich** [comment]
Wait, downsampling does not make sense: frequency resolution is determined by the trial width, not the sampling rate. What could work is shortening the window when you calculate the psd using the Welch method. Right now the window is the whole trial (from `tmin` to `tmax`) so Welch just becomes normal FFT. If we use a shorter window, we'll lower the frequency resolution (and presumably reduce the noise, I've never used Welch on actual data). 

BTW, I think we should either explicitly switch to FFT or use a shorter window anyway. But that is a whole different issue.

**Comment by dominikwelke** [comment]
now that youve tried so many things, i'd probably keep both options in a plotting def and let the user choose whether they want the ugly stem plot or the generic spectrum plot with grey background..

to the other discussion:
yes, downsampling isnt the solution.. would just limit our frequency range..

i wasnt really aware of the fft vs welch issue you raised. but tell me more about it - our frequency decomposition should make sense :)

in general i didnt think too much about the decomposition method: i took welch because its fast, narrow frequency bins to have the precise stimulation peak, and the full window because it resulted in the highest SNR (in the 40hz assr data i worked more on). 
this made sense to me: the full window has also more signal in it than shorter windows, and i think this linear increase in signal strength overcompensates the increase in the non-stationary noise components (except for the line noise).. 

but maybe this is not the optimal solution for our use case?

**Comment by kalenkovich** [comment]
> now that youve tried so many things, i'd probably keep both options in a plotting def and let the user choose whether they want the ugly stem plot or the generic spectrum plot with grey background..

I think that is a good idea for the eventual package/module but for the tutorial I would suggest picking one or another. We might want to even ditch the function altogether for the tutorial. What do you think?

**Comment by kalenkovich** [comment]
> yes, downsampling isnt the solution.. would just limit our frequency range..
> 
> i wasnt really aware of the fft vs welch issue you raised. but tell me more about it - our frequency decomposition should make sense :)
> 
> in general i didnt think too much about the decomposition method: i took welch because its fast, narrow frequency bins to have the precise stimulation peak, and the full window because it resulted in the highest SNR (in the 40hz assr data i worked more on).
> this made sense to me: the full window has also more signal in it than shorter windows, and i think this linear increase in signal strength overcompensates the increase in the non-stationary noise components (except for the line noise)..
> 
> but maybe this is not the optimal solution for our use case?

Welch, as I learned it, is meant to be a fancy periodogram: with overlapping windows and window functions. With one single window as in the current version, it is a fancy fft, not a fancy periodogram. I don't think this is inherently wrong, it is just weird :)

In my own aSSR/vSSR analysis, I use plain fft which is probably not the best solution either. This is not a question of what is right but rather of what is the simplest and least confusing to use in a tutorial. And the current welch is a little bit confusing, I think. We can leave it as is until the upstream PR though.

**Comment by dominikwelke** [comment]
i agree we have to choose - lets do what is most common in publications.
this would be stem plots, right? 

we could get rid of the overlay, and generally have fewer bins in the psd. 
this super fine version might be overkill for the tutorial anyway. we will likely get the stim freq in a bin thats not exactly cetered on it, but this should be captured by the code..

i think this would mean, we simply remove the `n_fft` and `n_overlap` parameters in the call of the welch function..

**Comment by dominikwelke** [comment]
my bad, just removing `n_fft` and `n_overlap` them doesnt work - not enough bins.. 
but `n_fft=10*sf` gives 10 bins per Hz, which should be enough.

**Comment by kalenkovich** [comment]
> i agree we have to choose - lets do what is most common in publications.
> this would be stem plots, right?

Not sure what is most popular, to be honest. I am doing a stem plot myself but I have mostly seen line plots in other articles.

**Comment by kalenkovich** [comment]
> my bad, just removing `n_fft` and `n_overlap` them doesnt work - not enough bins..
> but `n_fft=10*sf` gives 10 bins per Hz, which should be enough.

I'll play with these options and find something reasonable. We can always tweak it later.

**Comment by dominikwelke** [comment]
closed by #9
