### ISSUE TITLE
stats / analyses

### ISSUE THREAD

**Issue by dominikwelke** [dominikwelke/mne-python#5]
we might want to add additional / more advanced analyses 
eg. looking at harmonics

**Comment by dominikwelke** [comment]
so, i think this is the next and hopefully last crucial step to finish the tutorial.
what is your take on this: anything meaningful we can and want to show with this toy data?

my take:
- we could keep the ROI stuff, imo, because it should nicely correspond with the topo plot (and together it could nicely visualize how easy it might be to p-hack ;) - jokes apart, there could be a mini discussion of preregistering ROI's.
- we could add quantification of harmonics, even though it doesnt add much with these data

any more meaningful analysis might be done in a subsequent loop "you got an impression, now lets do some stats": 
- e.g. across subjects comparison or group level analysis (quite tasteless with n=2 but who cares)
- or comparing 12 vs 15 hz response. in the auditory domain, there is at least one paper that investigated which stim freq elicits maximal response - we might find this for the visual domain as well

**Comment by kalenkovich** [comment]
Hi, @dominikwelke! Sorry for disappearing yet again: I missed the comment above completely.

- ROI stuff - yes. I would also introduce it earlier and substitute ROI averaging for whole-head averaging in one of the plots.
- note on double-dipping not being OK - yes
- across subjects - I'd rather not if we can compare trials of one subject. It is much cooler to do it on a single-participant basis. It is partially the point of using SSVEP, I think.
- 12 vs 15 at the same frequency, that is: can we discriminate the conditions? - yes. The result is kind of obvious from the plots but makes sense as a prior hypothesis.
- 12 at 12 vs 15 at 15 - I am not sure if it makes sense in this case. Generally, I think this comparison is too specific for a tutorial.

**Comment by dominikwelke** [comment]
closed by ce6902f104da08c2ef1dcc6cad8e0a0317a6dd04
